name: Carz Customer Deployment

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tags"
        required: true
        default: v0.0.2-dev+1

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  RCT_NO_LAUNCH_PACKAGER: 1
  TELEGRAM_GROUP_ID: -1001924297028
  TELEGRAM_TOPIC_ID: 148
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  deploy-apk:
    name: Deploy apk
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          repository: "LibertyCarz/rn-carz-customer"
          token: ${{ secrets.GH_PAT }}
          ref: ${{ inputs.tag }}

      - name: Generate message
        run: |
          source .github/scripts/utils.sh
          echo "VALUE=$(get_message_information)" >> "$GITHUB_OUTPUT"
        id: message_information

      - name: send telegram message
        uses: PacificPromise/macos-telegram-action@main
        with:
          type: topic
          message: "Start APK: ${{ steps.message_information.outputs.VALUE }}"
