name: Carz Customer Deployment

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref"
        required: true
        default: v2.0.4

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  RCT_NO_LAUNCH_PACKAGER: 1
  TELEGRAM_GROUP_ID: -1001924297028
  TELEGRAM_TOPIC_ID: 148
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  deploy-apk:
    name: Deploy apk
    # runs-on: macos-latest
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          repository: "LibertyCarz/rn-carz-customer"
          token: ${{ secrets.GH_PAT }}
          ref: ${{ inputs.ref }}

      - name: Generate message
        run: |
          GITHUB_REF_NAME=${{ inputs.ref }}
          source .github/scripts/utils.sh
          echo "VALUE=$(get_message_information)" >> "$GITHUB_OUTPUT"
        id: message_information

      - name: send telegram message
        uses: PacificPromise/macos-telegram-action@main
        with:
          type: topic
          message: "Start APK: ${{ steps.message_information.outputs.VALUE }}"

      - name: Change version and build number
        run: bash .github/scripts/change_version_and_build_number.sh

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: $yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-

      - name: Run install
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
